---

- name: create backup directories
  file: owner=postgres group=postgres mode=0750 state=directory path={{ item }}
  with_items:
    - "{{ postgresql_backup_local_dir }}"
    - "{{ postgresql_backup_local_dir }}/bin"
    - "{{ postgresql_backup_active_dir }}"

- name: install backup scripts
  template: src={{ item }}.j2 dest={{ postgresql_backup_local_dir }}/bin/{{ item }} owner=postgres group=postgres mode=0750
  with_items:
    - wal_backup.sh
    - wal_archive.sh
    - backup_shedule.sh

- name: set WAL archive 
  template: src=ansible_backup.conf.j2 dest={{ postgresql_conf_dir }}/conf.d/ansible_backup.conf owner=postgres group=postgres backup=yes
  notify: restart postgresql

- name: schedule backups
  cron: name="psql Backup" cron_file=ansible_postgresql_backup user=postgres hour={{ postgresql_backup_hour | default(24) }} minute={{ postgresql_backup_minute | default(0) }} day={{ postgresql_backup_day | default(omit) }} month={{ postgresql_backup_month | default(omit) }} weekday={{ postgresql_backup_weekday | default(omit) }} job="{{ postgresql_backup_local_dir }}/bin/scheduled_backup.sh{{ ' && ' ~ postgresql_backup_post_command if postgresql_backup_post_command is defined else '' }}"

- name: schedule psql WAL backup
  cron: name="psql WAL backup" cron_file=ansible_postgresql_walbackup user=postgres job={{ postgresql_backup_local_dir }}/bin/backup_working_wal.sh
